api:
  auto_export_ngfw: true
  enabled: false
  host: 127.0.0.1
  port: 5000
  auth:
    enabled: false
    password: ""
    rate_limit:
      enabled: true
      requests_per_minute: 60
      burst: 10
  export:
    csv_enabled: true
    json_enabled: true
    text_enabled: true
    max_records: 10000
daemon:
  check_interval: 60s
  default_schedule: 1h
  enabled: true
  max_concurrent_feeds: 3
feeds:
- api_keys: &id001 []
  auto_detect_column: false
  column: 0
  delimiter: ','
  enabled: true
  encoding: utf-8
  has_header: true
  json_path: &id002 []
  limit: 100
  max_entries: 100
  max_retries: 3
  min_columns: 0
  name: URLhaus_URLs
  priority: 1
  rate_limit: 0
  retention: live
  schedule: 30m
  skip_malformed_lines: true
  timeout: 30
  type: text
  url: https://urlhaus.abuse.ch/downloads/text/
- api_keys: *id001
  auto_detect_column: false
  column: 0
  delimiter: ','
  enabled: true
  encoding: utf-8
  has_header: true
  json_path: *id002
  limit: 100
  max_entries: 100
  max_retries: 3
  min_columns: 0
  name: Feodo_IPs
  priority: 2
  rate_limit: 0
  retention: live
  schedule: 1h
  skip_malformed_lines: true
  timeout: 30
  type: text
  url: https://feodotracker.abuse.ch/downloads/ipblocklist.txt
- api_keys: *id001
  auto_detect_column: false
  column: url
  delimiter: ','
  enabled: true
  encoding: utf-8
  has_header: true
  json_path: *id002
  limit: 100
  max_entries: 100
  max_retries: 3
  min_columns: 3
  name: URLhaus_CSV
  priority: 1
  rate_limit: 0
  retention: live
  schedule: 45m
  skip_malformed_lines: true
  timeout: 30
  type: csv
  url: https://urlhaus.abuse.ch/downloads/csv/
- api_keys: *id001
  auto_detect_column: false
  column: sha256_hash
  delimiter: ','
  enabled: true
  encoding: utf-8
  has_header: true
  json_path: *id002
  limit: 100
  max_entries: 100
  max_retries: 3
  min_columns: 0
  name: MalwareBazaar_Hashes
  priority: 3
  rate_limit: 0
  retention: chaud
  schedule: 2h
  skip_malformed_lines: true
  timeout: 30
  type: csv
  url: https://bazaar.abuse.ch/export/csv/recent/
logging:
  backup_count: 5
  file: tinycti.log
  level: INFO
  max_size: 10MB
  compression: true
  compress_after: 24h
  retention_days: 30
  audit_enabled: true
  audit_file: tinycti-audit.log
max_file_size: 10485760
max_workers: 4
ngfw_export:
  auto_export_after_collection: true
  enabled: true
  generate_iptables_rules: true
  generate_pfsense_aliases: true
  output_dir: ngfw
output_dir: iocs
parallel_feeds: false
retention_policy:
  chaud_to_tiede: 7d
  froid_retention: 365d
  live_to_chaud: 24h
  tiede_to_froid: 30d
security:
  max_file_size: 52428800
  max_json_depth: 10
  user_agent: TinyCTI/1.0
  validate_ssl: true
authentication:
  users:
    admin:
      password_hash: "$2b$12$LQv9YB.JcTiWJ9L8JSUQie7KwKy7W3aEJJIr3k9KtKcvFfK6Dt5o2"  # default: admin123
      role: admin
  saml:
    enabled: false
    sp_entity_id: "tinycti"
    sp_assertion_consumer_service_url: "http://localhost:5000/saml/acs"
    idp_metadata_url: ""
    idp_sso_service_url: ""
    idp_x509_cert: ""
  openid:
    enabled: false
    client_id: ""
    client_secret: ""
    discovery_url: ""
    redirect_uri: "http://localhost:5000/openid/callback"

# Configuration de l'API interne d'exposition de fichiers .txt
internal_api:
  enabled: false  # Activez pour exposer les fichiers des buckets
  host: "127.0.0.1"
  port: 8080
  auth_token: ""  # Token d'accès optionnel - laissez vide pour accès libre
  rate_limit: 100  # Requêtes par minute

# Configuration SSL/TLS pour les feeds externes
# Ajoutez ces paramètres dans chaque feed selon vos besoins :
ssl_config_example:
  # Dans chaque feed, vous pouvez ajouter :
  ssl:
    verify: true          # Vérification SSL (true par défaut)
    cert_file: ""         # Fichier certificat client (optionnel)
    key_file: ""          # Fichier clé privée client (optionnel)
    ca_bundle: ""         # Bundle CA personnalisé (optionnel)
  
  # Authentification avancée pour APIs tierces :
  auth:
    type: "none"          # none, basic, bearer, api_key, oauth2
    username: ""          # Pour basic auth
    password: ""          # Pour basic auth
    token: ""             # Pour bearer token
    key: ""               # Pour api_key
    header: "X-API-Key"   # Header pour api_key (défaut: X-API-Key)
    client_id: ""         # Pour OAuth2
    client_secret: ""     # Pour OAuth2
    token_url: ""         # Pour OAuth2
  
  # Headers personnalisés
  headers:
    "User-Agent": "TinyCTI/1.0"
    # Ajoutez d'autres headers si nécessaire
